#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate one PokeCon Python Command module from safe, small templates."""
from __future__ import print_function

import os
import re


INVALID_SEGMENT = re.compile(r'[\\/:*?"<>|]')
INVALID_IDENTIFIER = re.compile(r'[^0-9A-Za-z_]')


def folder_segment(value):
    value = value.strip()
    if not value or value in (".", "..") or INVALID_SEGMENT.search(value):
        raise ValueError("Tag/folder cannot contain \\ / : * ? \" < > |")
    return value


def python_identifier(value):
    value = INVALID_IDENTIFIER.sub("_", value.strip())
    value = value.strip("_") or "PokeConCommand"
    if value[0].isdigit():
        value = "Command_" + value
    return value


def python_filename(value):
    value = os.path.basename(value.strip())
    if value.lower().endswith(".py"):
        value = value[:-3]
    return python_identifier(value) + ".py"


def command_path(commands_root, tags, filename):
    path = commands_root
    for tag in tags:
        path = os.path.join(path, folder_segment(tag))
    return os.path.join(path, python_filename(filename))


def template_source(kind, class_name, display_name, tags, steps, step_loop=True,
                    detection_targets=None, step_start=0, special_steps=None,
                    step_custom_bodies=None):
    class_name = python_identifier(class_name)
    display_name = display_name.replace("'", "\\'")
    tag_repr = repr(list(tags))
    detection_targets = list(detection_targets or [])
    target_repr = repr(detection_targets)
    header = """#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by PokeCon Dev Studio.  This file contains one command class only.

from Commands.PythonCommandBase import PythonCommand
from Commands.Keys import Button
import os


class {class_name}(PythonCommand):
    NAME = '{display_name}'
    TAGS = {tags}

    @classmethod
    def get_detection_targets(cls):
        # This is used only by Commands > Image match debug.  Normal command
        # execution never calls it.  Image Match Debug alone reads this list.
        # grayscale=True uses monochrome matching. reference_resolution scales
        # ROI/template from that capture resolution to the current camera size.
        return {targets}

""".format(class_name=class_name, display_name=display_name, tags=tag_repr,
           targets=target_repr)
    if kind == "Loop":
        return header + """    def __init__(self):
        super().__init__()
        self.loop_count = 0  # Visible in Command Watch

    def stop_checkpoint(self):
        # Call this repeatedly in loops and long-running steps.
        self.checkIfAlive()

    def do(self):
        while self.alive:
            self.stop_checkpoint()
            self.loop_count += 1
            print('{}: loop {}'.format(self.NAME, self.loop_count))
            # self.press(Button.A, duration=0.1, wait=0.1)
            self.wait(1.0)
"""
    if kind == "Step" or kind.startswith("Step (state") or kind.startswith("Step (nested"):
        step_custom_bodies = dict(step_custom_bodies or {})
        nested = kind.startswith("Step (nested")
        special_steps = list(special_steps or [])
        raw_steps = steps or ([{"key": "1", "label": "Chapter 1: preparation"}, {"key": "1_1", "label": "Child 1: check"}, {"key": "1_2", "label": "Child 2: action"}, {"key": "2", "label": "Chapter 2: finish"}] if nested else ["Chapter 1: preparation", "Chapter 2: action", "Chapter 3: finish"])
        step_items = []
        for index, item in enumerate(raw_steps):
            if isinstance(item, dict):
                step_items.append((str(item["key"]), str(item["label"])))
            else:
                step_items.append((str(index + int(step_start)), str(item)))
        step_lines = [item[1] for item in step_items]
        step_keys = [item[0] for item in step_items]
        special_keys = [python_identifier(item).lower() for item in special_steps]
        if nested:
            children = {key: [] for key in step_keys}
            for key in step_keys:
                if "_" in key:
                    children.setdefault(key.rsplit("_", 1)[0], []).append(key)
            labels = dict(step_items)
            nested_methods = []
            for key in step_keys:
                user_body = step_custom_bodies.get(key, "        # Write this step's command here / このStepの処理をここへ書きます。\n")
                if not user_body.endswith("\n"):
                    user_body += "\n"
                child_calls = "".join("""        result = self._step_{child}()
        if result is not None:
            return result
""".format(child=child) for child in children.get(key, []))
                nested_methods.append("""    def _step_{key}(self):
        # @pokedev-step: key={key}, mode=nested, role={role}
        # {label} / {label} の処理
        self.current_step = "{root}"
        self.current_substep = "{key}"
        self.stop_checkpoint()
        print('[STEP] {{}} / {{}}'.format(self.current_step, self.current_substep))
        # POKECON_STEP_USER_BEGIN {key}
{user_body}        # POKECON_STEP_USER_END {key}
{child_calls}        # Parent completion / 親Stepの終了処理
        return None

""".format(key=key, label=labels[key], root=key.split("_")[0], child_calls=child_calls, user_body=user_body,
             role="chapter" if children.get(key) else "leaf"))
            top_keys = [key for key in step_keys if "_" not in key]
            runner = """    def do(self):
        # Nested chapters / 親Stepが子Stepを順に実行します。
""" + "".join("""        result = self._step_{key}()
        if result is not None:
            return result
""".format(key=key) for key in top_keys)
            initializer = """    def __init__(self):
        super().__init__()
        self.current_step = ""
        self.current_substep = ""

"""
            return header + "    STEP_LABELS = {}\n    STEP_KEYS = {}\n    SPECIAL_STEP_KEYS = {}\n\n".format(repr(step_lines), repr(step_keys), repr(special_keys)) + initializer + "    def stop_checkpoint(self):\n        self.checkIfAlive()\n\n" + runner + "\n" + "".join(nested_methods)
        methods = []
        for number, (step_key, label) in enumerate(step_items):
            safe_label = label.replace("'", "\\'")
            user_body = step_custom_bodies.get(step_key, "        # Write this step's command here / このStepの処理をここへ書きます。\n")
            if not user_body.endswith("\n"):
                user_body += "\n"
            methods.append("""    def _step_{step_key}(self):
        # @pokedev-step: key={step_key}, mode=state, role=state
        # Step {step_key}: {label} / ステップ{step_key}: {label}
        self.stop_checkpoint()
        # self.press(Button.A, duration=0.1, wait=0.1)
        # POKECON_STEP_USER_BEGIN {step_key}
{user_body}        # POKECON_STEP_USER_END {step_key}
        # return None        # next step / 次のステップへ（標準）
        # return self.step   # repeat this step / このステップを繰り返す
        # return "{step_key}" # jump by step key / ステップ番号を指定して移動
        # return "{label}"  # jump by name / 名前を指定して移動
        return None

""".format(number=number, step_key=step_key, label=safe_label, user_body=user_body))
        helper = """    def stop_checkpoint(self):
        # Call in loops/long tasks. / ループ・長時間処理の途中で必ず呼びます。
        self.checkIfAlive()

"""
        if step_loop:
            runner = """    def do(self):
        # State-machine loop. / 各ステップ関数が次の遷移先を決める状態遷移ループです。
        while self.alive and 0 <= self.step < len(self.STEP_LABELS):
            self.stop_checkpoint()
            previous_step = self.step
            print('[STEP] {}/{}: {}'.format(self.step + 1, len(self.STEP_LABELS), self.STEP_LABELS[self.step]))
            next_step = getattr(self, "_step_{}".format(self.STEP_KEYS[self.step]))()
            if next_step is None:
                self.step += 1
            elif isinstance(next_step, str):
                if next_step in self.SPECIAL_STEP_KEYS:
                    next_step = getattr(self, "_special_{}".format(next_step))()
                    self.step = self.step + 1 if next_step is None else (self.STEP_KEYS.index(next_step) if next_step in self.STEP_KEYS else self.STEP_LABELS.index(next_step))
                else:
                    self.step = self.STEP_KEYS.index(next_step) if next_step in self.STEP_KEYS else self.STEP_LABELS.index(next_step)
            else:
                self.step = int(next_step)
            if self.step != previous_step:
                target_label = 'complete' if self.step >= len(self.STEP_LABELS) else self.step + 1
                print('[STEP] transition: {} -> {}'.format(previous_step + 1, target_label))
            self.wait(0.01)  # responsive UI/stop / UI・停止操作を応答可能に保つ

"""
        else:
            calls = "".join("        self._step_{}()\n".format(number) for number in range(len(step_lines)))
            runner = """    def do(self):
        self.stop_checkpoint()
""" + calls + "\n"
        initializer = """    def __init__(self):
        super().__init__()
        self.step = 0  # Visible in Command Watch

""" if step_loop else ""
        special_methods = "".join("""    def _special_{key}(self):
        # Special step: {label} / 特殊ステップ: {label}
        self.stop_checkpoint()
        # return "2" to resume a normal step / 通常ステップ2へ復帰する例
        return None

""".format(key=key, label=label) for key, label in zip(special_keys, special_steps))
        return header + "    STEP_LABELS = {}\n    STEP_KEYS = {}\n    SPECIAL_STEP_KEYS = {}\n\n".format(repr(step_lines), repr(step_keys), repr(special_keys)) + initializer + helper + runner + "".join(methods) + special_methods
    # One shot deliberately implements only the command entry point.
    return header + """    def do(self):
        self.checkIfAlive()
        # One-time processing goes here.
        result = 'completed'
        print('{}: {}'.format(self.NAME, result))
"""
