#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Shared safeguards for Python text edited or generated by DevStudio."""
from __future__ import print_function

import re


def _find_unescaped(text, needle, start=0):
    position = int(start)
    while True:
        position = text.find(needle, position)
        if position < 0:
            return -1
        backslashes = 0
        cursor = position - 1
        while cursor >= 0 and text[cursor] == "\\":
            backslashes += 1
            cursor -= 1
        if backslashes % 2 == 0:
            return position
        position += 1


def _multiline_string_continuation_rows(source):
    """Rows whose leading whitespace belongs to a multiline string value.

    This scanner intentionally runs before Python parsing: mixed indentation
    can make ``tokenize`` stop before a later multiline string is discovered.
    """
    rows = set()
    delimiter = None
    for number, line in enumerate(str(source).splitlines(True), 1):
        position = 0
        if delimiter is not None:
            rows.add(number)
            closing = _find_unescaped(line, delimiter)
            if closing < 0:
                continue
            position = closing + len(delimiter)
            delimiter = None
        quote = None
        while position < len(line):
            if quote is not None:
                if line[position] == "\\":
                    position += 2
                    continue
                if line[position] == quote:
                    quote = None
                position += 1
                continue
            if line[position] == "#":
                break
            candidate = line[position:position + 3]
            if candidate in ('"""', "'''"):
                closing = _find_unescaped(line, candidate, position + 3)
                if closing < 0:
                    delimiter = candidate
                    break
                position = closing + 3
                continue
            if line[position] in ('"', "'"):
                quote = line[position]
            position += 1
    return rows


def normalize_python_indentation(source, tabsize=4):
    """Replace tabs only in Python leading indentation with spaces.

    Tabs inside strings and after executable text are preserved. This makes
    pasted code, source/sample synchronization and the editor Tab key agree on
    four-space indentation without altering string data.
    """
    text = str(source or "")
    protected = _multiline_string_continuation_rows(text)
    lines = text.splitlines(True)
    normalized = []
    for number, line in enumerate(lines, 1):
        if number in protected:
            normalized.append(line)
            continue
        match = re.match(r"[ \t]+", line)
        if match and "\t" in match.group(0):
            line = match.group(0).expandtabs(int(tabsize)) + line[match.end():]
        normalized.append(line)
    return "".join(normalized)


def normalize_and_compile_python(source, filename="<DevStudio>"):
    """Normalize indentation and reject source that Python cannot compile."""
    normalized = normalize_python_indentation(source)
    compile(normalized, str(filename or "<DevStudio>"), "exec")
    return normalized